using DevExpress.Blazor;
using DxBlazorApplication1.Models;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace DxBlazorApplication1.Services.DataHelpers {
    public class AppointmentDataHelper {
        public static List<UniversityClass> GetAppointmentsWithResources() => appointmentsWithResources;

        public static List<UniversityClass> GetRecurrentAppointments() => recurrentAppointments;

        private static readonly List<UniversityClass> recurrentAppointments = new List<UniversityClass> {
            new UniversityClass { Id = 21, EventType = 1, StartTime = new DateTime(2025, 6, 1, 0, 0, 0), AllDay = true, Subject = "Classical Mechanics", Location = "Physics Building, Room 101", Description = "All-Day. Endless. Repeat each month. Single Resource. UTC +0", Label = 1, Status = 1, RecurrenceInfo = "<RecurrenceInfo Id=\"7e2b1c3a-4f6d-4b2a-9e1f-2a1b3c4d5e6f\" Start=\"2025-06-01T00:00:00\" Range=\"0\" Type=\"2\" Frequency=\"1\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1), TimeZoneId = "UTC" },
            new UniversityClass { Id = 22, EventType = 1, StartTime = new DateTime(2025, 6, 2, 9, 0, 0), EndTime = new DateTime(2025, 6, 2, 12, 0, 0), AllDay = false, Subject = "British Romanticism", Location = "Humanities Hall, Room 203", Description = "Ends by 2026-01-01. Repeat each Monday bi-weekly. Single Resource. UTC +0", Label = 2, Status = 2, RecurrenceInfo = "<RecurrenceInfo Id=\"1a9f8e7d-6c5b-4a3f-8e2d-7c6b5a4e3f2d\" Start=\"2025-06-02T09:00:00\" Range=\"2\" Type=\"1\" Frequency=\"2\" End=\"2026-01-01T00:00:00\" WeekDays=\"2\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2), TimeZoneId = "UTC" },
            new UniversityClass { Id = 23, EventType = 1, StartTime = new DateTime(2025, 6, 3, 13, 0, 0), EndTime = new DateTime(2025, 6, 3, 17, 0, 0), AllDay = false, Subject = "Chemical Bonding Workshop", Location = "Science Center, Lab A", Description = "5 occurrences. Repeat each month on 10th day. Single Resource. UTC +0", Label = 3, Status = 1, RecurrenceInfo = "<RecurrenceInfo Id=\"3c2d1e4f-5a6b-7c8d-9e0f-1a2b3c4d5e6f\" Start=\"2025-06-03T13:00:00\" Range=\"1\" Type=\"2\" Frequency=\"1\" WeekOfMonth=\"0\" OccurrenceCount=\"5\" DayNumber=\"10\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(3), TimeZoneId = "UTC" },
            new UniversityClass { Id = 24, EventType = 1, StartTime = new DateTime(2025, 6, 4, 0, 0, 0), AllDay = true, Subject = "Physical Chemistry", Location = "Science Lecture Hall 2", Description = "All-Day. Ends by 2025-08-01. Repeat each 5th week on week days. Multiple Resources. UTC +0", Label = 1, Status = 1, RecurrenceInfo = "<RecurrenceInfo Id=\"8f7e6d5c-4b3a-2f1e-9d8c-7b6a5e4d3c2b\" Start=\"2025-06-04T00:00:00\" Range=\"2\" Type=\"1\" Frequency=\"5\" WeekDays=\"62\" End=\"2025-08-01T00:00:00\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 3), TimeZoneId = "UTC" },
            new UniversityClass { Id = 25, EventType = 4, StartTime = new DateTime(2025, 6, 6, 10, 0, 0), AllDay = true, Subject = "Classical Mechanics (HOLIDAY)", Location = "", Description = "Deleted Occurrence. The second month. Single Resource. UTC +0", Label = 1, Status = 2, RecurrenceInfo = "<RecurrenceInfo Id=\"7e2b1c3a-4f6d-4b2a-9e1f-2a1b3c4d5e6f\" Index=\"2\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1), TimeZoneId = "UTC" },
            new UniversityClass { Id = 26, EventType = 4, StartTime = new DateTime(2025, 6, 7, 0, 0, 0), AllDay = true, Subject = "Physical Chemistry", Location = "Outside", Description = "Deleted Occurrence. The fifth day after start. Multiple Resources. UTC +0", Label = 1, Status = 4, RecurrenceInfo = "<RecurrenceInfo Id=\"8f7e6d5c-4b3a-2f1e-9d8c-7b6a5e4d3c2b\" Index=\"4\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 3), TimeZoneId = "UTC" },
            new UniversityClass { Id = 27, EventType = 0, StartTime = new DateTime(2025, 6, 8, 15, 0, 0), EndTime = new DateTime(2025, 6, 8, 18, 0, 0), AllDay = false, Subject = "Economic Policy & Literature", Location = "Main Auditorium", Description = "One-Time. Multiple Resources. UTC +0", Label = 2, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2, 4), TimeZoneId = "UTC" },
            new UniversityClass { Id = 28, EventType = 3, StartTime = new DateTime(2025, 6, 9, 0, 0, 0), AllDay = true, Subject = "Physical Chemistry", Location = "Communication Center", Description = "Changed Occurrence. The 7th occurrence after the start. Multiple Resources. UTC +0", Label = 1, Status = 1, RecurrenceInfo = "<RecurrenceInfo Id=\"8f7e6d5c-4b3a-2f1e-9d8c-7b6a5e4d3c2b\" Index=\"6\" />", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 2), TimeZoneId = "UTC" }
        };

        private static readonly List<UniversityClass> appointmentsWithResources = new List<UniversityClass> {
            new UniversityClass { Id = 1, EventType = 0, StartTime = new DateTime(2025, 6, 1, 0, 0, 0), EndTime = new DateTime(2025, 6, 2, 0, 0, 0), AllDay = true, Subject = "Quantum Physics", Location = "Physics Building, Room 101", Description = "One-Time. All-Day. Single Resource. UTC +0", Label = 1, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1), TimeZoneId = "UTC" },
            new UniversityClass { Id = 2, EventType = 0, StartTime = new DateTime(2025, 6, 2, 10, 0, 0), EndTime = new DateTime(2025, 6, 2, 13, 0, 0), AllDay = false, Subject = "Modern Poetry", Location = "Humanities Hall, Room 202", Description = "One-Time. Single Resource. UTC +0", Label = 2, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2), TimeZoneId = "UTC" },
            new UniversityClass { Id = 3, EventType = 0, StartTime = new DateTime(2025, 6, 3, 9, 0, 0), EndTime = new DateTime(2025, 6, 3, 15, 0, 0), AllDay = false, Subject = "Inorganic Chemistry Lab", Location = "Chemistry Lab 1B", Description = "One-Time. Single Resource. UTC +0", Label = 3, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(3), TimeZoneId = "UTC" },
            new UniversityClass { Id = 4, EventType = 0, StartTime = new DateTime(2025, 6, 4, 0, 0, 0), EndTime = new DateTime(2025, 6, 6, 0, 0, 0), AllDay = true, Subject = "Environmental Policy", Location = "Business Building, Room 303", Description = "One-Time. All-Day. Single Resource. UTC +0", Label = 1, Status = 4, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(4), TimeZoneId = "UTC" },
            new UniversityClass { Id = 5, EventType = 0, StartTime = new DateTime(2025, 6, 6, 14, 0, 0), EndTime = new DateTime(2025, 6, 6, 18, 0, 0), AllDay = false, Subject = "Physical Chemistry", Location = "Science Center, Room 201", Description = "One-Time. Two Resources. UTC +0", Label = 1, Status = 2, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 3), TimeZoneId = "UTC" },
            new UniversityClass { Id = 6, EventType = 0, StartTime = new DateTime(2025, 6, 7, 10, 0, 0), EndTime = new DateTime(2025, 6, 7, 12, 0, 0), AllDay = false, Subject = "Victorian Literature", Location = "Humanities Hall, Room 105", Description = "One-Time. Single Resource. UTC +3", Label = 2, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2), TimeZoneId = "Egypt Standard Time" },
            new UniversityClass { Id = 7, EventType = 0, StartTime = new DateTime(2025, 6, 8, 0, 0, 0), EndTime = new DateTime(2025, 6, 9, 0, 0, 0), AllDay = true, Subject = "Nuclear Reactions", Location = "Physics Lab A", Description = "One-Time. All-Day. Single Resource. UTC +3", Label = 1, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1), TimeZoneId = "Egypt Standard Time" },
            new UniversityClass { Id = 8, EventType = 0, StartTime = new DateTime(2025, 6, 9, 13, 0, 0), EndTime = new DateTime(2025, 6, 9, 16, 0, 0), AllDay = false, Subject = "Applied Microeconomics", Location = "Business Center, Room 110", Description = "One-Time. Single Resource. UTC +3", Label = 1, Status = 2, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(4), TimeZoneId = "Egypt Standard Time" },
            new UniversityClass { Id = 9, EventType = 0, StartTime = new DateTime(2025, 6, 10, 9, 0, 0), EndTime = new DateTime(2025, 6, 10, 13, 0, 0), AllDay = false, Subject = "Organic Chemistry", Location = "Lab C, Science Building", Description = "One-Time. Single Resource. UTC +3", Label = 1, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(3), TimeZoneId = "Egypt Standard Time" },
            new UniversityClass { Id = 10, EventType = 0, StartTime = new DateTime(2025, 6, 11, 0, 0, 0), EndTime = new DateTime(2025, 6, 13, 0, 0, 0), AllDay = true, Subject = "Poetry & Philosophy", Location = "Humanities Hall, Room 304", Description = "One-Time. All-Day. Two Resources. UTC +3", Label = 2, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2, 4), TimeZoneId = "Egypt Standard Time" },
            new UniversityClass { Id = 11, EventType = 0, StartTime = new DateTime(2025, 6, 14, 15, 0, 0), EndTime = new DateTime(2025, 6, 14, 18, 0, 0), AllDay = false, Subject = "Chemical Thermodynamics", Location = "Chemistry Lecture Hall", Description = "One-Time. Single Resource. UTC +3", Label = 1, Status = 3, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(3), TimeZoneId = "Turkey Standard Time" },
            new UniversityClass { Id = 12, EventType = 0, StartTime = new DateTime(2025, 6, 15, 0, 0, 0), EndTime = new DateTime(2025, 6, 16, 0, 0, 0), AllDay = true, Subject = "Philosophy of Science", Location = "Main Hall, Room 5", Description = "One-Time. All-Day. Two Resources. UTC +3", Label = 2, Status = 2, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 2), TimeZoneId = "Turkey Standard Time" },
            new UniversityClass { Id = 13, EventType = 0, StartTime = new DateTime(2025, 6, 16, 14, 0, 0), EndTime = new DateTime(2025, 6, 16, 18, 0, 0), AllDay = false, Subject = "Financial Markets", Location = "Economics Dept., Room 210", Description = "One-Time. Single Resource. UTC +3", Label = 1, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(4), TimeZoneId = "Turkey Standard Time" },
            new UniversityClass { Id = 14, EventType = 0, StartTime = new DateTime(2025, 6, 17, 10, 0, 0), EndTime = new DateTime(2025, 6, 17, 14, 0, 0), AllDay = false, Subject = "Experimental Poetry Lab", Location = "Literature Room 2C", Description = "One-Time. Single Resource. UTC +3", Label = 3, Status = 4, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2), TimeZoneId = "Turkey Standard Time" },
            new UniversityClass { Id = 15, EventType = 0, StartTime = new DateTime(2025, 6, 18, 0, 0, 0), EndTime = new DateTime(2025, 6, 19, 0, 0, 0), AllDay = true, Subject = "Science & Society", Location = "Main Auditorium", Description = "One-Time. All-Day. Three Resources. UTC +3", Label = 1, Status = 2, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 3, 4), TimeZoneId = "Turkey Standard Time" },
            new UniversityClass { Id = 16, EventType = 0, StartTime = new DateTime(2025, 6, 19, 11, 0, 0), EndTime = new DateTime(2025, 6, 19, 13, 0, 0), AllDay = false, Subject = "Macroeconomics", Location = "Econ Lecture Hall", Description = "One-Time. Single Resource. UTC +4", Label = 1, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(4), TimeZoneId = "Caucasus Standard Time" },
            new UniversityClass { Id = 17, EventType = 0, StartTime = new DateTime(2025, 6, 20, 13, 0, 0), EndTime = new DateTime(2025, 6, 20, 16, 0, 0), AllDay = false, Subject = "Creative Writing", Location = "Arts Center, Room 3A", Description = "One-Time. Single Resource. UTC +4", Label = 2, Status = 2, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(2), TimeZoneId = "Caucasus Standard Time" },
            new UniversityClass { Id = 18, EventType = 0, StartTime = new DateTime(2025, 6, 21, 0, 0, 0), EndTime = new DateTime(2025, 6, 22, 0, 0, 0), AllDay = true, Subject = "Interdisciplinary Science Fair", Location = "University Hall", Description = "One-Time. All-Day. Three Resources. UTC +4", Label = 3, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 3, 4), TimeZoneId = "Caucasus Standard Time" },
            new UniversityClass { Id = 19, EventType = 0, StartTime = new DateTime(2025, 6, 22, 10, 0, 0), EndTime = new DateTime(2025, 6, 22, 13, 0, 0), AllDay = false, Subject = "Chemical Safety Training", Location = "Science Lab B", Description = "One-Time. Single Resource. UTC +4", Label = 3, Status = 1, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(3), TimeZoneId = "Caucasus Standard Time" },
            new UniversityClass { Id = 20, EventType = 0, StartTime = new DateTime(2025, 6, 23, 0, 0, 0), EndTime = new DateTime(2025, 6, 24, 0, 0, 0), AllDay = true, Subject = "Joint Physics-Chemistry Workshop", Location = "Collaboration Hall", Description = "One-Time. All-Day. Two Resources. UTC +4", Label = 1, Status = 4, RecurrenceInfo = "", LecturerIds = DxSchedulerResourceIdCollection.ToXml(1, 3), TimeZoneId = "Caucasus Standard Time" }
        };
    }
}
